### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "12345"
}

### Update User
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
  "email": "test1@mail.com"
}

### Fetch One User
GET http://localhost:3000/auth/1

### Fetch Users
GET http://localhost:3000/auth?email=ipyka@gmail.com

### Remove User
DELETE http://localhost:3000/auth/